### ISSUE TITLE
CSS working on HTML

### ISSUE THREAD

**Issue by soobin-na** [FC-team4/fibaonachicken#4]
## Description
작성된 HTML에 CSS작업하겠습니다.

## Tasks
- [] Header 반응형으로 작업
- [] Box1 버튼 컬러 넣고 hover 지정
- [] Box1 box shadow넣기
- [] Box2 버튼 컬러 넣고 hover 지정
- [] Box2 box shadow넣기
- [] 전체적으로 반응형 되게 단위 지정하기
